CREATE TABLE Usuarios(Usuario VARCHAR(100),Contraseña VARCHAR(100), Bloqueado boolean);
INSERT INTO usuarios(Usuario, Contraseña, Bloqueado) VALUES ('Panchosky', 'hola123', false);
INSERT INTO usuarios(Usuario, Contraseña, Bloqueado) VALUES ('Ignacio', 'hola123', false);
INSERT INTO usuarios(Usuario, Contraseña, Bloqueado) VALUES ('Marion', 'hola123', false);
INSERT INTO usuarios(Usuario, Contraseña, Bloqueado) VALUES ('Profesor', 'hola123', false);
INSERT INTO usuarios(Usuario, Contraseña, Bloqueado) VALUES ('Nicolas', 'hola123', false);
INSERT INTO usuarios(Usuario, Contraseña, Bloqueado) VALUES ('Jaime', 'hola123', false);
INSERT INTO usuarios(Usuario, Contraseña, Bloqueado) VALUES ('Francisco', 'hola123', false);
INSERT INTO usuarios(Usuario, Contraseña, Bloqueado) VALUES ('Martin', 'hola123', false);
INSERT INTO usuarios(Usuario, Contraseña, Bloqueado) VALUES ('Gaspar', 'hola123', false);